-- Staged advanced player box scores (since ~1996). One row per player per game.
-- Renames every raw metric to snake_case and casts flags to booleans; metric
-- values are passed through as-is.
with source as (
    select * from {{ source('raw_nba', 'raw_nba_player_statistics_extended') }}
)

select
    gameId                                  as game_id,
    personId                                as person_id,
    firstName                               as first_name,
    lastName                                as last_name,
    gameDateTimeEst::timestamp              as game_datetime_est,
    gameType                                as game_type,
    gameLabel                               as game_label,
    gameSubLabel                            as game_sub_label,
    seriesGameNumber                        as series_game_number,
    playerteamId                            as player_team_id,
    playerteamCity                          as player_team_city,
    playerteamName                          as player_team_name,
    opponentteamId                          as opponent_team_id,
    opponentteamCity                        as opponent_team_city,
    opponentteamName                        as opponent_team_name,
    home = 1                                as is_home,
    win = 1                                 as is_win,
    startingPosition                        as starting_position,
    comment,
    try_cast(numMinutes as double)          as minutes_played,
    points,
    assists,
    reboundsTotal                           as rebounds_total,
    reboundsOffensive                       as rebounds_offensive,
    reboundsDefensive                       as rebounds_defensive,
    fieldGoalsMade                          as field_goals_made,
    fieldGoalsAttempted                     as field_goals_attempted,
    fieldGoalsPercentage                    as field_goals_percentage,
    threePointersMade                       as three_pointers_made,
    threePointersAttempted                  as three_pointers_attempted,
    threePointersPercentage                 as three_pointers_percentage,
    freeThrowsMade                          as free_throws_made,
    freeThrowsAttempted                     as free_throws_attempted,
    freeThrowsPercentage                    as free_throws_percentage,
    steals,
    blocks,
    blocksAgainst                           as blocks_against,
    turnovers,
    foulsPersonal                           as fouls_personal,
    foulsAgainst                            as fouls_against,
    plusMinusPoints                         as plus_minus_points,
    doubleDouble = 1                        as is_double_double,
    tripleDouble = 1                        as is_triple_double,
    estimatedOffensiveRating                as estimated_offensive_rating,
    offensiveRating                         as offensive_rating,
    spWorkOffensiveRating                   as sp_work_offensive_rating,
    estimatedDefensiveRating                as estimated_defensive_rating,
    defensiveRating                         as defensive_rating,
    spWorkDefensiveRating                   as sp_work_defensive_rating,
    estimatedNetRating                      as estimated_net_rating,
    netRating                               as net_rating,
    spWorkNetRating                         as sp_work_net_rating,
    assistPercentage                        as assist_percentage,
    assistToTurnoverRatio                   as assist_to_turnover_ratio,
    assistRatio                             as assist_ratio,
    offensiveReboundPercentage              as offensive_rebound_percentage,
    defensiveReboundPercentage              as defensive_rebound_percentage,
    reboundPercentage                       as rebound_percentage,
    teamTurnoverPercentage                  as team_turnover_percentage,
    estimatedTurnoverPercentage             as estimated_turnover_percentage,
    effectiveFieldGoalPercentage            as effective_field_goal_percentage,
    trueShootingPercentage                  as true_shooting_percentage,
    usagePercentage                         as usage_percentage,
    estimatedUsagePercentage                as estimated_usage_percentage,
    estimatedPace                           as estimated_pace,
    pace,
    pacePer40                               as pace_per_40,
    spWorkPace                              as sp_work_pace,
    playerImpactEstimate                    as player_impact_estimate,
    possessions,
    pointsOffTurnovers                      as points_off_turnovers,
    pointsSecondChance                      as points_second_chance,
    pointsFastBreak                         as points_fast_break,
    pointsInPaint                           as points_in_paint,
    opponentPointsOffTurnovers              as opponent_points_off_turnovers,
    opponentPointsSecondChance              as opponent_points_second_chance,
    opponentPointsFastBreak                 as opponent_points_fast_break,
    opponentPointsInPaint                   as opponent_points_in_paint,
    percentFieldGoalAttempts2Point          as percent_field_goal_attempts_2_point,
    percentFieldGoalAttempts3Point          as percent_field_goal_attempts_3_point,
    percentPoints2Point                     as percent_points_2_point,
    percentPoints2PointMidRange             as percent_points_2_point_mid_range,
    percentPoints3Point                     as percent_points_3_point,
    percentPointsFastBreak                  as percent_points_fast_break,
    percentPointsFreeThrow                  as percent_points_free_throw,
    percentPointsOffTurnovers               as percent_points_off_turnovers,
    percentPointsInPaint                    as percent_points_in_paint,
    percentAssisted2PointMade               as percent_assisted_2_point_made,
    percentUnassisted2PointMade             as percent_unassisted_2_point_made,
    percentAssisted3PointMade               as percent_assisted_3_point_made,
    percentUnassisted3PointMade             as percent_unassisted_3_point_made,
    percentAssistedFieldGoalsMade           as percent_assisted_field_goals_made,
    percentUnassistedFieldGoalsMade         as percent_unassisted_field_goals_made,
    percentTeamFieldGoalsMade               as percent_team_field_goals_made,
    percentTeamFieldGoalsAttempted          as percent_team_field_goals_attempted,
    percentTeamThreePointersMade            as percent_team_three_pointers_made,
    percentTeamThreePointersAttempted       as percent_team_three_pointers_attempted,
    percentTeamFreeThrowsMade               as percent_team_free_throws_made,
    percentTeamFreeThrowsAttempted          as percent_team_free_throws_attempted,
    percentTeamOffensiveRebounds            as percent_team_offensive_rebounds,
    percentTeamDefensiveRebounds            as percent_team_defensive_rebounds,
    percentTeamRebounds                     as percent_team_rebounds,
    percentTeamAssists                      as percent_team_assists,
    percentTeamTurnovers                    as percent_team_turnovers,
    percentTeamSteals                       as percent_team_steals,
    percentTeamBlocks                       as percent_team_blocks,
    percentTeamBlocksAgainst                as percent_team_blocks_against,
    percentTeamFoulsPersonal                as percent_team_fouls_personal,
    percentTeamFoulsDrawn                   as percent_team_fouls_drawn,
    percentTeamPoints                       as percent_team_points,
    ingested_at::timestamp                  as ingested_at
from source
