-- Staged traditional team box scores. One row per team per game.
with source as (
    select * from {{ source('raw_nba', 'raw_nba_team_statistics') }}
)

select
    gameId                              as game_id,
    teamId                              as team_id,
    teamCity                            as team_city,
    teamName                            as team_name,
    opponentTeamId                      as opponent_team_id,
    opponentTeamCity                    as opponent_team_city,
    opponentTeamName                    as opponent_team_name,
    gameDate::date                      as game_date,
    gameDateTimeEst::timestamp          as game_datetime_est,
    gameType                            as game_type,
    gameLabel                           as game_label,
    gameSubLabel                        as game_sub_label,
    seriesGameNumber                    as series_game_number,
    seed,
    coachId                             as coach_id,
    home = 1                            as is_home,
    win = 1                             as is_win,
    teamScore                           as team_score,
    opponentScore                       as opponent_score,
    numMinutes                          as minutes_played,
    assists,
    blocks,
    steals,
    fieldGoalsAttempted                 as field_goals_attempted,
    fieldGoalsMade                      as field_goals_made,
    fieldGoalsPercentage                as field_goals_percentage,
    threePointersAttempted              as three_pointers_attempted,
    threePointersMade                   as three_pointers_made,
    threePointersPercentage             as three_pointers_percentage,
    freeThrowsAttempted                 as free_throws_attempted,
    freeThrowsMade                      as free_throws_made,
    freeThrowsPercentage                as free_throws_percentage,
    reboundsOffensive                   as rebounds_offensive,
    reboundsDefensive                   as rebounds_defensive,
    reboundsTotal                       as rebounds_total,
    reboundsTeam                        as rebounds_team,
    foulsPersonal                       as fouls_personal,
    turnovers,
    turnoversTeam                       as turnovers_team,
    plusMinusPoints                     as plus_minus_points,
    q1Points                            as q1_points,
    q2Points                            as q2_points,
    q3Points                            as q3_points,
    q4Points                            as q4_points,
    ot1Points                           as ot1_points,
    ot2Points                           as ot2_points,
    otAllPoints                         as ot_all_points,
    benchPoints                         as bench_points,
    biggestLead                         as biggest_lead,
    biggestScoringRun                   as biggest_scoring_run,
    leadChanges                         as lead_changes,
    pointsFastBreak                     as points_fast_break,
    pointsFromTurnovers                 as points_from_turnovers,
    pointsInThePaint                    as points_in_the_paint,
    pointsSecondChance                  as points_second_chance,
    timesTied                           as times_tied,
    timeoutsRemaining                   as timeouts_remaining,
    seasonWins                          as season_wins,
    seasonLosses                        as season_losses,
    ingested_at::timestamp              as ingested_at
from source
