-- Staged advanced team box scores (since ~1996). One row per team per game.
-- Renames every raw metric to snake_case and casts flags to booleans; metric
-- values are passed through as-is.
with source as (
    select * from {{ source('raw_nba', 'raw_nba_team_statistics_extended') }}
)

select
    gameId                                  as game_id,
    teamId                                  as team_id,
    teamCity                                as team_city,
    teamName                                as team_name,
    opponentTeamId                          as opponent_team_id,
    opponentTeamCity                        as opponent_team_city,
    opponentTeamName                        as opponent_team_name,
    gameDateTimeEst::timestamp              as game_datetime_est,
    gameType                                as game_type,
    gameLabel                               as game_label,
    gameSubLabel                            as game_sub_label,
    seriesGameNumber                        as series_game_number,
    seed,
    home = 1                                as is_home,
    win = 1                                 as is_win,
    teamScore                               as team_score,
    opponentScore                           as opponent_score,
    numMinutes                              as minutes_played,
    assists,
    steals,
    blocks,
    blocksAgainst                           as blocks_against,
    fieldGoalsMade                          as field_goals_made,
    fieldGoalsAttempted                     as field_goals_attempted,
    fieldGoalsPercentage                    as field_goals_percentage,
    threePointersMade                       as three_pointers_made,
    threePointersAttempted                  as three_pointers_attempted,
    threePointersPercentage                 as three_pointers_percentage,
    freeThrowsMade                          as free_throws_made,
    freeThrowsAttempted                     as free_throws_attempted,
    freeThrowsPercentage                    as free_throws_percentage,
    reboundsOffensive                       as rebounds_offensive,
    reboundsDefensive                       as rebounds_defensive,
    reboundsTotal                           as rebounds_total,
    reboundsTeam                            as rebounds_team,
    foulsPersonal                           as fouls_personal,
    personalFoulsDrawn                      as personal_fouls_drawn,
    turnovers,
    turnoversTeam                           as turnovers_team,
    plusMinusPoints                         as plus_minus_points,
    q1Points                                as q1_points,
    q2Points                                as q2_points,
    q3Points                                as q3_points,
    q4Points                                as q4_points,
    ot1Points                               as ot1_points,
    ot2Points                               as ot2_points,
    otAllPoints                             as ot_all_points,
    benchPoints                             as bench_points,
    biggestLead                             as biggest_lead,
    biggestScoringRun                       as biggest_scoring_run,
    leadChanges                             as lead_changes,
    pointsFastBreak                         as points_fast_break,
    pointsFromTurnovers                     as points_from_turnovers,
    pointsInThePaint                        as points_in_the_paint,
    pointsSecondChance                      as points_second_chance,
    timesTied                               as times_tied,
    timeoutsRemaining                       as timeouts_remaining,
    seasonWins                              as season_wins,
    seasonLosses                            as season_losses,
    estimatedOffensiveRating                as estimated_offensive_rating,
    offensiveRating                         as offensive_rating,
    estimatedDefensiveRating                as estimated_defensive_rating,
    defensiveRating                         as defensive_rating,
    estimatedNetRating                      as estimated_net_rating,
    netRating                               as net_rating,
    assistPercentage                        as assist_percentage,
    assistToTurnoverRatio                   as assist_to_turnover_ratio,
    assistRatio                             as assist_ratio,
    offensiveReboundPercentage              as offensive_rebound_percentage,
    defensiveReboundPercentage              as defensive_rebound_percentage,
    reboundPercentage                       as rebound_percentage,
    teamTurnoverPercentage                  as team_turnover_percentage,
    effectiveFieldGoalPercentage            as effective_field_goal_percentage,
    trueShootingPercentage                  as true_shooting_percentage,
    estimatedPace                           as estimated_pace,
    pace,
    pacePer40                               as pace_per_40,
    possessions,
    playerImpactEstimate                    as player_impact_estimate,
    pointsOffTurnovers                      as points_off_turnovers,
    opponentPointsOffTurnovers              as opponent_points_off_turnovers,
    opponentPointsSecondChance              as opponent_points_second_chance,
    opponentPointsFastBreak                 as opponent_points_fast_break,
    opponentPointsInPaint                   as opponent_points_in_paint,
    percentFieldGoalAttempts2Point          as percent_field_goal_attempts_2_point,
    percentFieldGoalAttempts3Point          as percent_field_goal_attempts_3_point,
    percentPoints2Point                     as percent_points_2_point,
    percentPoints2PointMidRange             as percent_points_2_point_mid_range,
    percentPoints3Point                     as percent_points_3_point,
    percentPointsFastBreak                  as percent_points_fast_break,
    percentPointsFreeThrow                  as percent_points_free_throw,
    percentPointsOffTurnovers               as percent_points_off_turnovers,
    percentPointsInPaint                    as percent_points_in_paint,
    percentAssisted2PointMade               as percent_assisted_2_point_made,
    percentUnassisted2PointMade             as percent_unassisted_2_point_made,
    percentAssisted3PointMade               as percent_assisted_3_point_made,
    percentUnassisted3PointMade             as percent_unassisted_3_point_made,
    percentAssistedFieldGoalsMade           as percent_assisted_field_goals_made,
    percentUnassistedFieldGoalsMade         as percent_unassisted_field_goals_made,
    freeThrowAttemptRate                    as free_throw_attempt_rate,
    opponentEffectiveFieldGoalPercentage    as opponent_effective_field_goal_percentage,
    opponentFreeThrowAttemptRate            as opponent_free_throw_attempt_rate,
    opponentTurnoverPercentage              as opponent_turnover_percentage,
    opponentOffensiveReboundPercentage      as opponent_offensive_rebound_percentage,
    ingested_at::timestamp                  as ingested_at
from source
